require "highlander.spec"
require "highlander.options"
require "highlander.keymaps"

spec "highlander.mason"
spec "highlander.lspconfig"
spec "highlander.treesitter"
spec "highlander.cmp"
spec "highlander.null-ls"

spec "highlander.colorscheme"
spec "highlander.lualine"
spec "highlander.telescope"
spec "highlander.autopairs"
spec "highlander.comment"
spec "highlander.indentline"
spec "highlander.illuminate"
spec "highlander.devicons"
spec "highlander.diffview"
spec "highlander.gitsigns"

require "highlander.lazy"
